%function calib_gui_normal,


cell_list = {};


%-------- Begin editable region -------------%
%-------- Begin editable region -------------%


fig_number = 1;

title_figure = 'Camera Projector Calibration Toolbox - Standard Version';

clear fc cc kc KK
kc = zeros(5,1);
%clearwin;

cell_list{1,4} = {'Ray plane intersection','cam_proj_3d_points'};
cell_list{3,4} = {'Exit',['disp(''Bye. To run again, type cam_proj_gui.''); close(' num2str(fig_number) ');']}; %{'Exit','calib_gui;'};
cell_list{1,3} = {'Set Projector''s calib. images','define_Projector_Images;'};
cell_list{2,4} = {'Show calib results','ext_calib_cam_proj;'};
cell_list{2,1} = {'Calibrate the projector','calibrate_projector;'};
cell_list{3,3} = {'Load Cam-Proj calib','load Cam_Proj_calib; '};
cell_list{3,1} = {'Add/Suppress images','dummyCode'};%[
%                                             'active_images_cpy = active_images; '   ...
%                                             'add_suppress; '                        ...
%                                             'nonOrigin_active_images= find((Origin_active_images-active_images)==-1); '...
%                                             'if ~isempty(nonOrigin_active_images), ' ... 
%                                                 'sprintf ( ''Images [''); '        ...
%                                                 'for i=nonOrigin_active_images; '   ...
%                                                     'sprintf ( '' %d'',i); '       ...
%                                                 'end; '                             ...    
%                                                 'sprintf ( '' ] where not used for the initial camera calibration. \n '');'...
%                                                 'sprintf ( ''In order to use it/them Set another Projector''s calib. images \n '');'...
%                                                 'active_images = active_images_cpy; '...
%                                             'end;'...
%                                         ]};
cell_list{2,2} = {'Reproject',[                                                             ...
                                'if ~exist( ''Projector_calibrated_check''), '              ...
                                    'sprintf ( ''Calibrate the projector first. \n''); '   ...
                                    'return; '                                              ...
                                'end; '                                                     ...
                                'dont_ask=0; '                                              ...
                                'reproject_calib; '                                         ...
                              ]};
cell_list{3,2} = {'Save',[
                          'if exist(''Projector_calibrated_check'') '   ...
                            'save Cam_Proj_calib; '                     ...
                          'else '                                       ...
                            'display(''Non data to save''); '           ...
                            'return; '                                  ...
                          'end; '                                       ...
                          'display done;'                               ...
                          ]};

cell_list{1,2} = {'Load Camera Calibration',[                                            ...
                                                'clear all; '                            ...
                                                'loading_calib; '                        ...
                                                'Origin_active_images = active_images; ' ... 
                                            ]};
cell_list{2,3} = {'Analyse error',[                                                             ...
                                    'if ~exist( ''Projector_calibrated_check''), '              ...
                                        'sprintf ( ''Calibrate the projector first. \n''); '   ...
                                        'return; '                                              ...
                                    'end; '                                                     ...
                                    ' analyse_error2;'                                          ...
                                   ]};
cell_list{1,1} = {'Camera Calibration GUI' ,[
                                            'calib_gui_normal; '        ...
                                            'uiwait(fig_number);'       ...
                                            'cam_proj_gui'              ...
                                         ]};


show_window(cell_list,fig_number,title_figure,180,18,0,'clean',12);


%-------- End editable region -------------%
%-------- End editable region -------------%

